os: linux
dist: focal
language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9-dev'
  - 'nightly'
  - pip install -r requirements.txt
  
script
  - pytest

install:
  - sudo apt -y install python3-distutils
  - sudo apt -y install python3-pip
  - sudo apt -y install git
  - git clone https: //github.com/kivy/buildozer.git
  - python3 -m site
